src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200)]
    private $Libelle;

    #[ORM\Column(type: 'integer')]
    private $stock;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'produit')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Entree::class)]
    private $entree;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Sortie::class)]
    private $sortie;

    #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private $categorie;

    public function __toString() {
        return $this->Libelle;
    }

    public function __construct()
    {
        $this->entree = new ArrayCollection();
        $this->sortie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Entree>
     */
    public function getEntree(): Collection
    {
        return $this->entree;
    }

    public function addEntree(Entree $entree): self
    {
        if (!$this->entree->contains($entree)) {
            $this->entree[] = $entree;
            $entree->setProduit($this);
        }

        return $this;
    }

    public function removeEntree(Entree $entree): self
    {
        if ($this->entree->removeElement($entree)) {
            // set the owning side to null (unless already changed)
            if ($entree->getProduit() === $this) {
                $entree->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSortie(): Collection
    {
        return $this->sortie;
    }

    public function addSortie(Sortie $sortie): self
    {
        if (!$this->sortie->contains($sortie)) {
            $this->sortie[] = $sortie;
            $sortie->setProduit($this);
        }

        return $this;
    }

    public function removeSortie(Sortie $sortie): self
    {
        if ($this->sortie->removeElement($sortie)) {
            // set the owning side to null (unless already changed)
            if ($sortie->getProduit() === $this) {
                $sortie->setProduit(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Libelle', TextType::class)
            ->add('stock',TextType::class)
            ->add('user',EntityType::class, ['class' => User::class,
                                             'choice_label' => 'label',
                                             'multiple' => true,
                                             'expanded' => false])
            ->add('categorie', EntityType::class, ['class' => Categorie::class,
                                                   'choice_label' => 'label',
                                                   'multiple' => true,
                                                   'expanded' => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\CategorieRepository;
use App\Repository\UserRepository;

class ProduitController extends AbstractController
{
    #[Route('/produit', name: 'app_produit')]
    public function index(ProduitRepository $produitRepository, CategorieRepository $categorieRepository,UserRepository $userRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
            'categories' => $categorieRepository->findAll(),
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/ajouter', name: 'app_produit_ajouter', methods: ['GET', 'POST'])]
    public function ajouter(Request $request, ProduitRepository $produitRepository): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $produitRepository->add($produit, true);

            return $this->redirectToRoute('app_produit', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/index.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    
}

templates/produit/index.html.twig
{% extends 'accueil/index.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
<div class="col-12 tm-block-col">
    <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
        <h2 class="tm-block-title">Liste des produits</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#id</th>
                        <th scope="col">Libelle</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Categorie</th>
                    </tr>
                </thead>
                <tbody>
                    {% for produit in produits %}
                        <tr>
                            <td>{{ produit.id }}</td>
                            <td>{{ produit.libelle }}</td>
                            <td>{{ produit.stock }}</td>
                            <td>{{ produit.categorie }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">Aucun enregistrement trouve</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
     <div class="container tm-mt-big tm-mb-big">
      <div class="row">
        <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
            <div class="row">
              <div class="col-12">
                <h2 class="tm-block-title d-inline-block">Ajouter un produit</h2>
              </div>
            </div>
            <div class="row tm-edit-product-row">
              <div class="col-xl-6 col-lg-6 col-md-12">
                <form name="produit" action="" class="tm-edit-product-form">
                  <div class="form-group mb-3">
                    <label
                      for="name"
                      >Libelle
                    </label>
                    <input id="name" name="Libelle" type="text" value="" class="form-control validate"
                      required/>
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="categorie" name="categorie"
                      >Categorie</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="categorie" value=""
                    >
                      <option selected>Selectionner une categorie</option>
                    {% for categorie in categories %}
                      <option>{{categorie.nomCat}}</option>
                    {% else %}
                      <option selected>Aucune categorie enregistree</option>
                    {% endfor %}
                    </select>
                  </div>
              </div>
              <div class="col-xl-6 col-lg-6 col-md-12 mx-auto mb-4">
                <div class="row">
                      <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="stock"
                            >Stock
                          </label>
                          <input
                            id="stock"
                            name="stock"
                            type="text"
                            class="form-control validate"
                            required
                          />
                        </div>
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="user"
                      >Utilisateur</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="user" value="" name="user"
                    >
                      <option selected>{{ app.user.id }} {{ app.user.prenomUser }} {{ app.user.nomUser }}</option>
                    </select>
                  </div>
              </div>
              <div class="col-12">
                    <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ button_label|default('Ajouter') }}</button>
              </div>
            </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>  



{% endblock %}